spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    job:
      enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false