spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
