spring:
  datasource:
    url: jdbc:mysql://localhost:3307/med
    username: root
    password: your_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8088
  error:
    whitelabel:
      enabled: false