export const questions = [
    {
        id: 1,
        section_title: 'Choose one option for each questionnaire item.',
        question: 'In general, would you say your health is:',
        answer: 5,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'exelent',
        boundary_value_red: 'poor',
    },
    {
        id: 2,
        section_title: 'Choose one option for each questionnaire item.',
        question: 'Compared to one year ago, how would you rate your health in general now?',
        answer: 5,
        answer_green: 1,
        answer_light_green: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Much better now than one year ago',
        boundary_value_red: 'Much worse now than one year ago',
    },
    {
        id: 3,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Vigorous activities, such as running, lifting heavy objects, participating in strenuous sports',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 4,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Moderate activities, such as moving a table, pushing a vacuum cleaner, bowling, or playing golf',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 5,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Lifting or carrying groceries',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 6,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Climbing several flights of stairs',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 7,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Climbing one flight of stairs',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 8,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Bending, kneeling, or stooping',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 9,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Walking more than a mile',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 10,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Walking several blocks',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 11,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Walking one block',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 12,
        section_title: 'The following items are about activities you might do during a typical day. Does your health now limit you in these activities? If so, how much?',
        question: 'Bathing or dressing yourself',
        answer: 3,
        answer_green: 3,
        answer_light_green: 0,
        answer_light_yellow: 2,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No, not limited at all',
        boundary_value_red: 'Yes, limited a lot',
    },
    {
        id: 13,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of your physical health?',
        question: 'Cut down the amount of time you spent on work or other activities',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 14,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of your physical health?',
        question: 'Accomplished less than you would like',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 15,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of your physical health?',
        question: 'Were limited in the kind of work or other activities',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 16,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of your physical health?',
        question: 'Had difficulty performing the work or other activities (for example, it took extra effort)',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 17,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of any emotional problems (such as feeling depressed or anxious)?',
        question: 'Cut down the amount of time you spent on work or other activities',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 18,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of any emotional problems (such as feeling depressed or anxious)?',
        question: 'Accomplished less than you would like',
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 19,
        section_title: 'During the past 4 weeks, have you had any of the following problems with your work or other regular daily activities as a result of any emotional problems (such as feeling depressed or anxious)?',
        question: "Didn't do work or other activities as carefully as usual",
        answer: 2,
        answer_green: 2,
        answer_light_green: 0,
        answer_light_yellow: 0,
        answer_yellow: 0,
        answer_orange: 0,
        answer_red: 1,
        boundary_value_green: 'No',
        boundary_value_red: 'Yes',
    },
    {
        id: 20,
        section_title: '',
        question: 'During the past 4 weeks, to what extent has your physical health or emotional problems interfered with your normal social activities with family, friends, neighbors, or groups?',
        answer: 5,
        answer_green: 1,
        answer_light_green: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Not at all',
        boundary_value_red: 'Extremely',
    },
    {
        id: 21,
        section_title: '',
        question: 'How much bodily pain have you had during the past 4 weeks?',
        answer: 6,
        answer_green: 1,
        answer_light_green: 2,
        answer_light_yellow: 3,
        answer_yellow: 4,
        answer_orange: 5,
        answer_red: 6,
        boundary_value_green: 'None',
        boundary_value_red: 'Very severe',
    },
    {
        id: 22,
        section_title: '',
        question: 'During the past 4 weeks, how much did pain interfere with your normal work (including both work outside the home and housework)?',
        answer: 5,
        answer_green: 1,
        answer_light_green: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Not at all',
        boundary_value_red: 'Extremely',
    },
    {
        id: 23,
        section_title: 'These questions are about how you feel and how things have been with you during the past 4 weeks. For each question, please give the one answer that comes closest to the way you have been feeling. How much of the time during the past 4 weeks...',
        question: 'Did you feel full of pep?',
        answer: 6,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 4,
        answer_orange: 5,
        answer_red: 6,
        boundary_value_green: 'All of the time',
        boundary_value_red: 'None of the time',
    },
    {
        id: 24,
        section_title: '',
        question: 'Have you been a very nervous person?',
        answer: 6,
        answer_green: 6,
        answer_light_green: 5,
        answer_light_yellow: 4,
        answer_yellow: 3,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 25,
        section_title: '',
        question: 'Have you felt so down in the dumps that nothing could cheer you up?',
        answer: 6,
        answer_green: 6,
        answer_light_green: 5,
        answer_light_yellow: 4,
        answer_yellow: 3,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 26,
        section_title: '',
        question: 'Have you felt calm and peaceful?',
        answer: 6,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 4,
        answer_orange: 5,
        answer_red: 6,
        boundary_value_green: 'All of the time',
        boundary_value_red: 'None of the time',
    },
    {
        id: 27,
        section_title: '',
        question: 'Did you have a lot of energy?',
        answer: 6,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 4,
        answer_orange: 5,
        answer_red: 6,
        boundary_value_green: 'All of the time',
        boundary_value_red: 'None of the time',
    },
    {
        id: 28,
        section_title: '',
        question: 'Have you felt downhearted and blue?',
        answer: 6,
        answer_green: 6,
        answer_light_green: 5,
        answer_light_yellow: 4,
        answer_yellow: 3,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 29,
        section_title: '',
        question: 'Did you feel worn out?',
        answer: 6,
        answer_green: 6,
        answer_light_green: 5,
        answer_light_yellow: 4,
        answer_yellow: 3,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 30,
        section_title: '',
        question: 'Have you been a happy person?',
        answer: 6,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 4,
        answer_orange: 5,
        answer_red: 6,
        boundary_value_green: 'All of the time',
        boundary_value_red: 'None of the time',
    },
    {
        id: 31,
        section_title: '',
        question: 'Did you feel tired?',
        answer: 6,
        answer_green: 6,
        answer_light_green: 5,
        answer_light_yellow: 4,
        answer_yellow: 3,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 32,
        section_title: '',
        question: 'During the past 4 weeks, how much of the time has your physical health or emotional problems interfered with your social activities (like visiting with friends, relatives, etc.)?',
        answer: 5,
        answer_green: 5,
        answer_light_green: 4,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'None of the time',
        boundary_value_red: 'All of the time',
    },
    {
        id: 33,
        section_title: 'How TRUE or FALSE is each of the following statements for you.',
        question: 'I seem to get sick a little easier than other people',
        answer: 5,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Definitely true',
        boundary_value_red: 'Definitely false',
    },
    {
        id: 34,
        section_title: '',
        question: 'I am as healthy as anybody I know',
        answer: 5,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Definitely true',
        boundary_value_red: 'Definitely false',
    },
    {
        id: 35,
        section_title: '',
        question: 'I expect my health to get worse',
        answer: 5,
        answer_green: 5,
        answer_light_grin: 4,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 2,
        answer_red: 1,
        boundary_value_green: 'Definitely false',
        boundary_value_red: 'Definitely true',
    },
    {
        id: 36,
        section_title: '',
        question: 'My health is excellent',
        answer: 5,
        answer_green: 1,
        answer_light_grin: 2,
        answer_light_yellow: 3,
        answer_yellow: 0,
        answer_orange: 4,
        answer_red: 5,
        boundary_value_green: 'Definitely true',
        boundary_value_red: 'Definitely false',
    },
]